[TK-common] ci: gitAction cache 옵션을 npm -> pnpm 으로 변경

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -29,7 +29,7 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: "^18.x"
-          cache: "npm"
+          cache: "pnpm"
           
       - name: Install pnpm
         run: npm install -g pnpm
@@ -45,8 +45,11 @@ jobs:
             ${{ runner.os }}-pnpm-store-
 
       - name: Install dependencies
-        working-directory: ../pnpm-lock.yaml
-        run: pnpm install --frozen-lockfile --only=prod
+        run: |
+          if [ ! -f pnpm-lock.yaml ]; then
+            echo "Error: Lock file is missing!" && exit 1
+          fi 
+          pnpm install --frozen-lockfile --prod
         
       - name: Build
         run: pnpm build
